# Generated by Django 6.0.3 on 2026-04-04 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("sort_order", models.IntegerField(default=0)),
                ("filter_category_ids", models.JSONField(blank=True, null=True)),
                (
                    "filter_video_type",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("filter_min_duration", models.IntegerField(blank=True, null=True)),
                ("filter_max_duration", models.IntegerField(blank=True, null=True)),
                ("filter_max_age_days", models.IntegerField(blank=True, null=True)),
                (
                    "filter_play_state",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feeds",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscription_id",
                    models.CharField(
                        blank=True, max_length=256, null=True, unique=True
                    ),
                ),
                ("channel_id", models.CharField(max_length=256, unique=True)),
                ("channel_title", models.CharField(max_length=256)),
                ("channel_description", models.TextField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("subscription_date", models.DateTimeField(blank=True, null=True)),
                (
                    "subscriber_count",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("topics", models.JSONField(blank=True, null=True)),
                ("topic_in_topic_cache", models.BooleanField(default=False)),
                (
                    "last_published_at",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("videos_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["channel_title"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="subscriptions.category",
                    ),
                ),
            ],
            options={
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.category",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_category",
                "unique_together": {("subscription", "category")},
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                through="subscriptions.SubscriptionCategory",
                to="subscriptions.category",
            ),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=32, unique=True)),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                (
                    "thumbnail_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("video_type", models.CharField(blank=True, max_length=32, null=True)),
                ("playback_progress", models.IntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        db_column="channel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="subscriptions.subscription",
                        to_field="channel_id",
                    ),
                ),
            ],
            options={
                "db_table": "videos",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "video",
                    models.OneToOneField(
                        db_column="video_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.video",
                        to_field="video_id",
                    ),
                ),
            ],
            options={
                "db_table": "queue_items",
                "ordering": ["sort_order"],
            },
        ),
    ]
