# Generated by Django 6.0.7 on 2026-08-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_video_watched_locally"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="uploads_backfilled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="uploads_page_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
